import Link from "next/link";

export default function NotFound() {
  return (
    <main className="error-page">
      <p className="eyebrow">404 / ROUTE NOT FOUND</p>
      <h1>This operational view does not exist.</h1>
      <p>Case URLs are generated by the API and remain organization-scoped.</p>
      <Link className="button button-primary" href="/cases">
        Return to cases
      </Link>
    </main>
  );
}
