#!/usr/bin/env python3
# ruff: noqa: E501
"""Generate the checked TypeScript case client from the FastAPI OpenAPI document.

This intentionally has no generator dependency: the OpenAPI producer is already
part of the locked API runtime and the generated files are reviewable artifacts.
Run with ``--check`` in tests/CI to fail when API contract changes have not been
regenerated and committed.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = REPOSITORY_ROOT / "packages" / "api-client"
OPENAPI_OUTPUT = PACKAGE_ROOT / "openapi.json"
CLIENT_OUTPUT = PACKAGE_ROOT / "src" / "generated.ts"


def _schema() -> dict[str, Any]:
    """Build the public API document directly from the FastAPI application."""
    sys.path.insert(0, str(REPOSITORY_ROOT / "services" / "api"))
    from netops_api.core.config import Environment, Settings
    from netops_api.main import create_app

    return create_app(
        Settings(environment=Environment.TEST, service_name="netops-api-contract-generator")
    ).openapi()


def _typescript_client(schema: Mapping[str, Any]) -> str:
    """Render TypeScript types and a small authenticated case client from OpenAPI."""
    components = _mapping(schema.get("components"))
    schemas = _mapping(components.get("schemas"))
    type_lines = [
        "/* This file is generated by scripts/generate-api-client.py. Do not edit. */",
        "",
    ]
    for name, definition in sorted(schemas.items()):
        if isinstance(definition, Mapping):
            type_lines.extend(_render_named_schema(str(name), definition))
            type_lines.append("")

    paths = _mapping(schema.get("paths"))
    required_paths = {
        "/v1/cases",
        "/v1/cases/{case_id}",
        "/v1/cases/{case_id}/timeline",
        "/v1/cases/{case_id}/transitions",
        "/v1/cases/{case_id}/resolution",
        "/v1/cases/{case_id}/feedback",
        "/v1/cases/{case_id}/config-preview",
        "/v1/cases/{case_id}/artifacts/upload-intents",
        "/v1/cases/{case_id}/artifacts/upload-intents/{intent_id}/complete",
        "/v1/cases/{case_id}/artifacts/status",
        "/v1/events",
    }
    missing_paths = sorted(required_paths - set(paths))
    if missing_paths:
        raise ValueError(f"OpenAPI is missing required case paths: {', '.join(missing_paths)}")
    _validate_event_stream_operation(_mapping(paths["/v1/events"]))

    type_lines.extend(
        [
            "export interface ApiClientOptions {",
            "  baseUrl: string;",
            "  accessToken: () => string | Promise<string>;",
            "  fetch?: typeof fetch;",
            "}",
            "",
            "export interface CaseListOptions {",
            "  cursor?: string;",
            "  limit?: number;",
            "  q?: string;",
            "  severity?: CaseResponse['severity'];",
            "  state?: CaseState;",
            "}",
            "",
            "export interface CaseEventStreamEventData {",
            "  event_id: string;",
            "  case_id: string;",
            "  event_type: string;",
            "  aggregate_version: number;",
            "  transition_id: string | null;",
            "  actor_id: string;",
            "  correlation_id: string;",
            "  occurred_at: string;",
            "}",
            "",
            "export interface CaseEventStreamEvent {",
            "  id: string;",
            "  event: 'case';",
            "  data: CaseEventStreamEventData;",
            "}",
            "",
            "export interface CaseEventStreamOptions {",
            "  lastEventId?: string;",
            "  limit?: number;",
            "  signal?: AbortSignal;",
            "}",
            "",
            "export class NetOpsApiError extends Error {",
            "  readonly status: number;",
            "  readonly body: unknown;",
            "",
            "  constructor(status: number, body: unknown) {",
            "    super(`NetOps API request failed with status ${status}.`);",
            "    this.name = 'NetOpsApiError';",
            "    this.status = status;",
            "    this.body = body;",
            "  }",
            "}",
            "",
            "export class NetOpsCaseClient {",
            "  private readonly fetchImpl: typeof fetch;",
            "",
            "  constructor(private readonly options: ApiClientOptions) {",
            "    this.fetchImpl = options.fetch ?? fetch;",
            "  }",
            "",
            "  listCases(options: number | CaseListOptions = 50): Promise<CaseListResponse> {",
            "    const normalized = typeof options === 'number' ? { limit: options } : options;",
            "    const parameters = new URLSearchParams({ limit: String(normalized.limit ?? 50) });",
            "    if (normalized.cursor !== undefined) parameters.set('cursor', normalized.cursor);",
            "    if (normalized.q !== undefined) parameters.set('q', normalized.q);",
            "    if (normalized.severity !== undefined) parameters.set('severity', normalized.severity);",
            "    if (normalized.state !== undefined) parameters.set('state', normalized.state);",
            "    return this.request('GET', `/v1/cases?${parameters.toString()}`);",
            "  }",
            "",
            "  createCase(body: CreateCaseRequest, idempotencyKey: string): Promise<CaseResponse> {",
            "    return this.request('POST', '/v1/cases', body, { 'Idempotency-Key': idempotencyKey });",
            "  }",
            "",
            "  getCase(caseId: string): Promise<CaseDetailResponse> {",
            "    return this.request('GET', `/v1/cases/${encodeURIComponent(caseId)}`);",
            "  }",
            "",
            "  getCaseTimeline(caseId: string): Promise<CaseTimelineEntryResponse[]> {",
            "    return this.request('GET', `/v1/cases/${encodeURIComponent(caseId)}/timeline`);",
            "  }",
            "",
            "  transitionCase(caseId: string, body: TransitionCaseRequest): Promise<CaseResponse> {",
            "    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/transitions`, body);",
            "  }",
            "",
            "  resolveCase(caseId: string, body: ResolveCaseRequest): Promise<CaseResponse> {",
            "    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/resolution`, body);",
            "  }",
            "",
            "  requestCaseFeedback(caseId: string, body: CaseFeedbackRequest): Promise<CaseResponse> {",
            "    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/feedback`, body);",
            "  }",
            "",
            "  previewCaseConfig(caseId: string, body: ConfigPreviewRequest): Promise<ConfigPreviewResponse> {",
            "    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/config-preview`, body);",
            "  }",
            "",
            "  createArtifactUploadIntent(",
            "    caseId: string,",
            "    body: ArtifactUploadIntentRequest,",
            "  ): Promise<ArtifactUploadCapabilityResponse> {",
            "    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/artifacts/upload-intents`, body);",
            "  }",
            "",
            "  completeArtifactUploadIntent(",
            "    caseId: string,",
            "    intentId: string,",
            "  ): Promise<ArtifactUploadCompletionResponse> {",
            "    return this.request(",
            "      'POST',",
            "      `/v1/cases/${encodeURIComponent(caseId)}/artifacts/upload-intents/${encodeURIComponent(intentId)}/complete`,",
            "    );",
            "  }",
            "",
            "  listCaseArtifactStatuses(caseId: string): Promise<CaseArtifactStatusListResponse> {",
            "    return this.request('GET', `/v1/cases/${encodeURIComponent(caseId)}/artifacts/status`);",
            "  }",
            "",
            "  async *streamCaseEvents(",
            "    options: CaseEventStreamOptions = {},",
            "  ): AsyncGenerator<CaseEventStreamEvent> {",
            "    const limit = options.limit ?? 100;",
            "    const parameters = new URLSearchParams({ limit: String(limit) });",
            "    const accessToken = await this.options.accessToken();",
            "    const response = await this.fetchImpl(",
            "      `${this.options.baseUrl.replace(/\\/$/, '')}/v1/events?${parameters.toString()}` ,",
            "      {",
            "        headers: {",
            "          Accept: 'text/event-stream',",
            "          Authorization: `Bearer ${accessToken}`,",
            "          ...(options.lastEventId === undefined",
            "            ? {}",
            "            : { 'Last-Event-ID': options.lastEventId }),",
            "        },",
            "        signal: options.signal,",
            "      },",
            "    );",
            "    if (!response.ok) {",
            "      throw new NetOpsApiError(response.status, await response.json());",
            "    }",
            "    if (response.body === null) {",
            "      return;",
            "    }",
            "    const reader = response.body.getReader();",
            "    const decoder = new TextDecoder();",
            "    let pending = '';",
            "    while (true) {",
            "      const chunk = await reader.read();",
            "      if (chunk.done) {",
            "        pending += decoder.decode();",
            "        break;",
            "      }",
            "      pending += decoder.decode(chunk.value, { stream: true });",
            "      let separator = pending.indexOf('\\n\\n');",
            "      while (separator >= 0) {",
            "        const frame = pending.slice(0, separator);",
            "        pending = pending.slice(separator + 2);",
            "        const event = this.parseCaseEventFrame(frame);",
            "        if (event !== undefined) {",
            "          yield event;",
            "        }",
            "        separator = pending.indexOf('\\n\\n');",
            "      }",
            "    }",
            "    const event = this.parseCaseEventFrame(pending);",
            "    if (event !== undefined) {",
            "      yield event;",
            "    }",
            "  }",
            "",
            "  private async request<T>(",
            "    method: string,",
            "    path: string,",
            "    body?: unknown,",
            "    headers: Record<string, string> = {},",
            "  ): Promise<T> {",
            "    const accessToken = await this.options.accessToken();",
            "    const response = await this.fetchImpl(`${this.options.baseUrl.replace(/\\/$/, '')}${path}`, {",
            "      method,",
            "      headers: {",
            "        Accept: 'application/json',",
            "        Authorization: `Bearer ${accessToken}`,",
            "        ...(body === undefined ? {} : { 'Content-Type': 'application/json' }),",
            "        ...headers,",
            "      },",
            "      body: body === undefined ? undefined : JSON.stringify(body),",
            "    });",
            "    const responseBody: unknown = await response.json();",
            "    if (!response.ok) {",
            "      throw new NetOpsApiError(response.status, responseBody);",
            "    }",
            "    return responseBody as T;",
            "  }",
            "",
            "  private parseCaseEventFrame(frame: string): CaseEventStreamEvent | undefined {",
            "    let id: string | undefined;",
            "    let event: string | undefined;",
            "    const data: string[] = [];",
            "    for (const line of frame.split('\\n')) {",
            "      if (line.startsWith('id: ')) id = line.slice(4);",
            "      else if (line.startsWith('event: ')) event = line.slice(7);",
            "      else if (line.startsWith('data: ')) data.push(line.slice(6));",
            "    }",
            "    if (id === undefined || event !== 'case' || data.length === 0) {",
            "      return undefined;",
            "    }",
            "    return {",
            "      id,",
            "      event: 'case',",
            "      data: JSON.parse(data.join('\\n')) as CaseEventStreamEventData,",
            "    };",
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(type_lines)


def _render_named_schema(name: str, schema: Mapping[str, Any]) -> list[str]:
    if schema.get("type") == "object" or "properties" in schema:
        required = set(_string_list(schema.get("required")))
        lines = [f"export interface {name} {{"]
        for property_name, property_schema in sorted(_mapping(schema.get("properties")).items()):
            optional = "" if property_name in required else "?"
            lines.append(
                f"  {_property_name(str(property_name))}{optional}: {_ts_type(_mapping(property_schema))};"
            )
        additional_properties = schema.get("additionalProperties")
        if isinstance(additional_properties, Mapping):
            lines.append(f"  [key: string]: {_ts_type(additional_properties)};")
        lines.append("}")
        return lines
    return [f"export type {name} = {_ts_type(schema)};"]


def _validate_event_stream_operation(operation: Mapping[str, Any]) -> None:
    """Ensure the generated recovery method matches the checked OpenAPI operation."""
    get_operation = _mapping(operation.get("get"))
    parameters = _mapping_parameter_names(get_operation.get("parameters"))
    if "Last-Event-ID" not in parameters or "limit" not in parameters:
        raise ValueError("OpenAPI event stream must expose Last-Event-ID and limit parameters.")
    responses = _mapping(get_operation.get("responses"))
    if "200" not in responses:
        raise ValueError("OpenAPI event stream must document a successful replay response.")


def _ts_type(schema: Mapping[str, Any]) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return reference.rsplit("/", maxsplit=1)[-1]
    enum = schema.get("enum")
    if isinstance(enum, list):
        return " | ".join(json.dumps(value) for value in enum)
    for composite in ("anyOf", "oneOf", "allOf"):
        values = schema.get(composite)
        if isinstance(values, list):
            return " | ".join(_ts_type(_mapping(value)) for value in values)
    type_name = schema.get("type")
    if type_name == "array":
        return f"{_ts_type(_mapping(schema.get('items')))}[]"
    if type_name in {"integer", "number"}:
        return "number"
    if type_name == "boolean":
        return "boolean"
    if type_name == "null":
        return "null"
    if type_name == "string":
        return "string"
    if type_name == "object":
        additional_properties = schema.get("additionalProperties")
        if isinstance(additional_properties, Mapping):
            return f"Record<string, {_ts_type(additional_properties)}>"
        return "Record<string, unknown>"
    return "unknown"


def _mapping(value: object) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _string_list(value: object) -> list[str]:
    return [item for item in value if isinstance(item, str)] if isinstance(value, list) else []


def _mapping_parameter_names(value: object) -> set[str]:
    if not isinstance(value, list):
        return set()
    return {
        parameter["name"]
        for parameter in value
        if isinstance(parameter, Mapping) and isinstance(parameter.get("name"), str)
    }


def _property_name(value: str) -> str:
    return value if value.isidentifier() else json.dumps(value)


def _write_or_check(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text() if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"Generated API contract is stale: {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"Updated {path.relative_to(REPOSITORY_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of regenerating stale files")
    args = parser.parse_args()
    schema = _schema()
    openapi = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    client = _typescript_client(schema)
    checks = (
        _write_or_check(OPENAPI_OUTPUT, openapi, check=args.check),
        _write_or_check(CLIENT_OUTPUT, client, check=args.check),
    )
    return 0 if all(checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
