/* This file is generated by scripts/generate-api-client.py. Do not edit. */

export interface ArtifactStatusResponse {
  artifact_id: string;
  artifact_kind: string;
  status: string;
  status_updated_at: string;
}

export interface ArtifactUploadCapabilityResponse {
  artifact_id: string;
  expires_at: string;
  intent_id: string;
  required_headers: Record<string, string>;
  upload_url: string;
}

export interface ArtifactUploadCompletionResponse {
  already_completed: boolean;
  artifact_id: string;
  completed_at: string;
}

export interface ArtifactUploadIntentRequest {
  artifact_kind: "network-configuration" | "incident-audio";
  content_length: number;
  content_type: string;
  original_filename?: string | null;
  sha256: string;
}

export interface AuthenticatedIdentityResponse {
  asset_ids: string[];
  organization_id: string;
  roles: CaseRole[];
  subject: string;
}

export interface CaseArtifactStatusListResponse {
  items: ArtifactStatusResponse[];
}

export interface CaseDetailResponse {
  case: CaseResponse;
  timeline: CaseTimelineEntryResponse[];
}

export interface CaseFeedbackRequest {
  expected_version: number;
  note: string;
}

export interface CaseInputRequest {
  content: Record<string, JsonValue>;
  input_kind: string;
}

export interface CaseListResponse {
  items: CaseResponse[];
  next_cursor?: string | null;
}

export interface CaseResponse {
  asset_id: string | null;
  category: string | null;
  created_at: string;
  created_by_actor_id: string | null;
  id: string;
  severity: string;
  state: CaseState;
  title: string;
  updated_at: string;
  version: number;
}

export type CaseRole = "org_admin" | "operator" | "approver" | "auditor" | "integration_admin" | "platform_admin";

export type CaseState = "new" | "investigating" | "diagnosed" | "fix_proposed" | "needs_information" | "confirmed" | "resolved" | "learned";

export interface CaseTimelineEntryResponse {
  actor_id: string;
  aggregate_version: number;
  approval_id: string | null;
  correlation_id: string;
  event_id: string;
  event_type: string;
  from_state: CaseState | null;
  knowledge_item_id: string | null;
  note: string | null;
  occurred_at: string;
  to_state: CaseState | null;
  transition_id: string | null;
  verification_note: string | null;
}

export interface ConfigPreviewRequest {
  config: string;
}

export interface ConfigPreviewResponse {
  redacted_content: string;
  redacted_content_sha256: string;
  redaction_version: string;
  report: RedactionReportResponse;
}

export interface CreateCaseRequest {
  asset_id?: string | null;
  category?: string | null;
  input?: CaseInputRequest | null;
  severity: "low" | "medium" | "high" | "critical";
  title: string;
}

export interface ErrorBody {
  code: string;
  details?: Record<string, unknown> | null;
  message: string;
  request_id: string;
}

export interface ErrorEnvelope {
  error: ErrorBody;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type JsonValue = unknown;

export interface RedactionReportResponse {
  redacted_line_count: number;
  rules: RedactionRuleSummaryResponse[];
  source_line_count: number;
}

export interface RedactionRuleSummaryResponse {
  line_count: number;
  occurrence_count: number;
  rule_id: string;
}

export interface ResolveCaseRequest {
  expected_version: number;
  verification_note: string;
}

export interface TransitionCaseRequest {
  approval_id?: string | null;
  expected_version: number;
  knowledge_item_id?: string | null;
  note?: string | null;
  to_state: CaseState;
  verification_note?: string | null;
}

export interface ValidationError {
  loc: string | number[];
  msg: string;
  type: string;
}

export interface ApiClientOptions {
  baseUrl: string;
  accessToken: () => string | Promise<string>;
  fetch?: typeof fetch;
}

export interface CaseListOptions {
  cursor?: string;
  limit?: number;
  q?: string;
  severity?: CaseResponse['severity'];
  state?: CaseState;
}

export interface CaseEventStreamEventData {
  event_id: string;
  case_id: string;
  event_type: string;
  aggregate_version: number;
  transition_id: string | null;
  actor_id: string;
  correlation_id: string;
  occurred_at: string;
}

export interface CaseEventStreamEvent {
  id: string;
  event: 'case';
  data: CaseEventStreamEventData;
}

export interface CaseEventStreamOptions {
  lastEventId?: string;
  limit?: number;
  signal?: AbortSignal;
}

export class NetOpsApiError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(status: number, body: unknown) {
    super(`NetOps API request failed with status ${status}.`);
    this.name = 'NetOpsApiError';
    this.status = status;
    this.body = body;
  }
}

export class NetOpsCaseClient {
  private readonly fetchImpl: typeof fetch;

  constructor(private readonly options: ApiClientOptions) {
    this.fetchImpl = options.fetch ?? fetch;
  }

  listCases(options: number | CaseListOptions = 50): Promise<CaseListResponse> {
    const normalized = typeof options === 'number' ? { limit: options } : options;
    const parameters = new URLSearchParams({ limit: String(normalized.limit ?? 50) });
    if (normalized.cursor !== undefined) parameters.set('cursor', normalized.cursor);
    if (normalized.q !== undefined) parameters.set('q', normalized.q);
    if (normalized.severity !== undefined) parameters.set('severity', normalized.severity);
    if (normalized.state !== undefined) parameters.set('state', normalized.state);
    return this.request('GET', `/v1/cases?${parameters.toString()}`);
  }

  createCase(body: CreateCaseRequest, idempotencyKey: string): Promise<CaseResponse> {
    return this.request('POST', '/v1/cases', body, { 'Idempotency-Key': idempotencyKey });
  }

  getCase(caseId: string): Promise<CaseDetailResponse> {
    return this.request('GET', `/v1/cases/${encodeURIComponent(caseId)}`);
  }

  getCaseTimeline(caseId: string): Promise<CaseTimelineEntryResponse[]> {
    return this.request('GET', `/v1/cases/${encodeURIComponent(caseId)}/timeline`);
  }

  transitionCase(caseId: string, body: TransitionCaseRequest): Promise<CaseResponse> {
    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/transitions`, body);
  }

  resolveCase(caseId: string, body: ResolveCaseRequest): Promise<CaseResponse> {
    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/resolution`, body);
  }

  requestCaseFeedback(caseId: string, body: CaseFeedbackRequest): Promise<CaseResponse> {
    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/feedback`, body);
  }

  previewCaseConfig(caseId: string, body: ConfigPreviewRequest): Promise<ConfigPreviewResponse> {
    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/config-preview`, body);
  }

  createArtifactUploadIntent(
    caseId: string,
    body: ArtifactUploadIntentRequest,
  ): Promise<ArtifactUploadCapabilityResponse> {
    return this.request('POST', `/v1/cases/${encodeURIComponent(caseId)}/artifacts/upload-intents`, body);
  }

  completeArtifactUploadIntent(
    caseId: string,
    intentId: string,
  ): Promise<ArtifactUploadCompletionResponse> {
    return this.request(
      'POST',
      `/v1/cases/${encodeURIComponent(caseId)}/artifacts/upload-intents/${encodeURIComponent(intentId)}/complete`,
    );
  }

  listCaseArtifactStatuses(caseId: string): Promise<CaseArtifactStatusListResponse> {
    return this.request('GET', `/v1/cases/${encodeURIComponent(caseId)}/artifacts/status`);
  }

  async *streamCaseEvents(
    options: CaseEventStreamOptions = {},
  ): AsyncGenerator<CaseEventStreamEvent> {
    const limit = options.limit ?? 100;
    const parameters = new URLSearchParams({ limit: String(limit) });
    const accessToken = await this.options.accessToken();
    const response = await this.fetchImpl(
      `${this.options.baseUrl.replace(/\/$/, '')}/v1/events?${parameters.toString()}` ,
      {
        headers: {
          Accept: 'text/event-stream',
          Authorization: `Bearer ${accessToken}`,
          ...(options.lastEventId === undefined
            ? {}
            : { 'Last-Event-ID': options.lastEventId }),
        },
        signal: options.signal,
      },
    );
    if (!response.ok) {
      throw new NetOpsApiError(response.status, await response.json());
    }
    if (response.body === null) {
      return;
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let pending = '';
    while (true) {
      const chunk = await reader.read();
      if (chunk.done) {
        pending += decoder.decode();
        break;
      }
      pending += decoder.decode(chunk.value, { stream: true });
      let separator = pending.indexOf('\n\n');
      while (separator >= 0) {
        const frame = pending.slice(0, separator);
        pending = pending.slice(separator + 2);
        const event = this.parseCaseEventFrame(frame);
        if (event !== undefined) {
          yield event;
        }
        separator = pending.indexOf('\n\n');
      }
    }
    const event = this.parseCaseEventFrame(pending);
    if (event !== undefined) {
      yield event;
    }
  }

  private async request<T>(
    method: string,
    path: string,
    body?: unknown,
    headers: Record<string, string> = {},
  ): Promise<T> {
    const accessToken = await this.options.accessToken();
    const response = await this.fetchImpl(`${this.options.baseUrl.replace(/\/$/, '')}${path}`, {
      method,
      headers: {
        Accept: 'application/json',
        Authorization: `Bearer ${accessToken}`,
        ...(body === undefined ? {} : { 'Content-Type': 'application/json' }),
        ...headers,
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const responseBody: unknown = await response.json();
    if (!response.ok) {
      throw new NetOpsApiError(response.status, responseBody);
    }
    return responseBody as T;
  }

  private parseCaseEventFrame(frame: string): CaseEventStreamEvent | undefined {
    let id: string | undefined;
    let event: string | undefined;
    const data: string[] = [];
    for (const line of frame.split('\n')) {
      if (line.startsWith('id: ')) id = line.slice(4);
      else if (line.startsWith('event: ')) event = line.slice(7);
      else if (line.startsWith('data: ')) data.push(line.slice(6));
    }
    if (id === undefined || event !== 'case' || data.length === 0) {
      return undefined;
    }
    return {
      id,
      event: 'case',
      data: JSON.parse(data.join('\n')) as CaseEventStreamEventData,
    };
  }
}
